# Generated by Django 4.2.13 on 2024-07-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_builder', '0005_alter_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='current_employees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='size_range',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_employees_estimate',
            field=models.IntegerField(),
        ),
    ]
