# Generated by Django 4.2.13 on 2024-07-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_builder', '0007_alter_company_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
